config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :job_has_functions
  resources :meeting_has_members
  resources :members
  resources :jobs
  resources :meetings
  resources :functions
  resources :agendas
  resources :meetings

   root 'sessions#new'

  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

end

app/models/function.rb
class Function < ActiveRecord::Base

	has_many :job_has_functions
	has_many :jobs, through: :job_has_function

end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  before_action :set_function, only: [:show, :edit, :update, :destroy]

  # GET /functions
  # GET /functions.json
  def index
    if logged_in?
      @functions = Function.all
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /functions/1
  # GET /functions/1.json
  def show
    unless logged_in?
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /functions/new
  def new
    if logged_in? && current_user.admin?
      @function = Function.new
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /functions/1/edit
  def edit
    unless logged_in? && current_user.admin?
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # POST /functions
  # POST /functions.json
  def create
    if logged_in? && current_user.admin?
      @function = Function.new(function_params)

      respond_to do |format|
        if @function.save
          format.html { redirect_to @function }
          format.json { render :show, status: :created, location: @function }
        else
          format.html { render :new }
          format.json { render json: @function.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # PATCH/PUT /functions/1
  # PATCH/PUT /functions/1.json
  def update
    if logged_in? && current_user.admin?
      respond_to do |format|
        if @function.update(function_params)
          format.html { redirect_to @function }
          format.json { render :show, status: :ok, location: @function }
        else
          format.html { render :edit }
          format.json { render json: @function.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger]= 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # DELETE /functions/1
  # DELETE /functions/1.json
  def destroy
    if logged_in? && current_user.admin?
      @function.destroy
      respond_to do |format|
        format.html { redirect_to functions_url }
        format.json { head :no_content }
      end
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_function
      @function = Function.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def function_params
      params.require(:function).permit(:function_name, :function_module, :function_url)
    end
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/functions/_form.html.erb
<div class="text-center well">
    <%= form_for(@function) do |f| %>

      <div class="field form-group">
        <%= f.label :function_name, 'Função' %><br>
        <%= f.text_field :function_name, class:'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :function_module, 'Módulo' %><br>
        <%= f.text_field :function_module, class:'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :function_url, 'Url' %><br>
        <%= f.text_field :function_url, class:'form-control' %>
      </div>
      <div class="actions text-center">
        <%= f.submit 'Criar Função', class:'btn btn-success' %>
      </div><br>

      <div class="text-center">
        <%= link_to 'Voltar', functions_path, class: "btn btn-default" %>
      </div>

    <% end %>
</div>

app/views/functions/edit.html.erb
<div class="text-center col-md-12 well">
  <div class="row"><h1 class="enfeite-off"><%= link_to 'Editar Função', agenda_path %></h1></div>
</div><br><br><br><br><br><br>

<%= render 'form' %>

app/views/functions/index.html.erb
<div class="container col-md-12 text-center well">
    <div class="row"><h1>Funções</h1></div>
</div>

<div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="col-md-4">Função</th>
          <th class="col-md-4">Módulo</th>
          <th class="col-md-4">Url</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @functions.each do |function| %>
          <tr>
            <td class="col-md-4"><%= function.function_name %></td>
            <td class="col-md-4"><%= function.function_module %></td>
            <td class="col-md-4"><%= function.function_url %></td>
            <td><%= link_to 'Show', function %></td>
            <td><%= link_to 'Edit', edit_function_path(function) %></td>
            <td><%= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

<br>

<% if logged_in? && current_user.admin? %>
    <div class="container">
        <div class="row text-center col-md-12"><%= link_to 'New Function', new_function_path, class: "btn btn-primary" %></div>
    </div>
<% end %>

app/views/functions/new.html.erb
<div class="text-center col-md-12 well">
  <div class="row"><h1>Nova Função</h1></div>
</div><br><br><br><br><br><br>

<%= render 'form' %>

app/views/functions/show.html.erb
<div class="text-center col-md-12 well">
    <p>
      <strong>Função:</strong><br>
      <%= @function.function_name %>
    </p>

    <p>
      <strong>Módulo:</strong><br>
      <%= @function.function_module %>
    </p>

    <p>
      <strong>Url:</strong><br>
      <%= @function.function_url %>
    </p>
</div>

<div class="row text-center ">
    <%= link_to 'Editar', edit_function_path(@function), class:'btn btn-default' %>
    <%= link_to 'Voltar', functions_path, class:'btn btn-default' %>
</div>