config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :job_has_functions
  resources :meeting_has_members
  resources :members
  resources :jobs
  resources :meetings
  resources :functions
  resources :agendas
  resources :meetings

   root 'sessions#new'

  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

end

app/models/job.rb
class Job < ActiveRecord::Base

 	validates :job_name, presence: true, length: { maximum: 100 }

	has_many :job_has_functions
 	has_many :functions, through: :job_has_function
	belongs_to :member

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    if logged_in?
      @jobs = Job.all
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    unless logged_in?
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /jobs/new
  def new
    if logged_in? && current_user.admin?
      @job = Job.new
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /jobs/1/edit
  def edit
    unless logged_in? && current_user.admin?
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    if logged_in? && current_user.admin?
      @job = Job.new(job_params)

      respond_to do |format|
        if @job.save
          format.html { redirect_to @job }
          format.json { render :show, status: :created, location: @job }
        else
          format.html { render :new }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    if logged_in? && current_user.admin?
      respond_to do |format|
        if @job.update(job_params)
          format.html { redirect_to @job }
          format.json { render :show, status: :ok, location: @job }
        else
          format.html { render :edit }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    if logged_in? && current_user.admin?
      @job.destroy
      respond_to do |format|
        format.html { redirect_to jobs_url }
        format.json { head :no_content }
      end
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_name)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="text-center well">
<%= form_for(@job) do |f| %>

  <div class="field form-group">
    <%= f.label :job_name, 'Cargo'%><br>
    <%= f.text_field :job_name, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Criar Cargo', class:'btn btn-success' %>
  </div><br>

      <div class="col-md-12 text-center">
        <%= link_to 'Voltar', jobs_path, class: "btn btn-default" %>
      </div><br><br>

<% end %>

</div>

app/views/jobs/edit.html.erb
<div class="text-center col-md-12 well">
  <div class="row"><h1 class="enfeite-off"><%= link_to 'Editar Cargo', job_path %></h1></div>
</div><br><br><br><br><br><br>

<%= render 'form' %>

app/views/jobs/index.html.erb
<div class="container col-md-12 text-center well">
    <div class="row"><h1>Cargos</h1></div>
</div>

<div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="col-md-12">Cargo</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td class="col-md-12"><%= job.job_name %></td>
            <td><%= link_to 'Show', job %></td>
            <td><%= link_to 'Edit', edit_job_path(job) %></td>
            <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

<br>

<% if logged_in? && current_user.admin? %>
    <div class="container">
        <div class="row col-md-12 text-center"><%= link_to 'Novo Cargo', new_job_path, class: "btn btn-primary" %></div>
    </div>
<% end %>

app/views/jobs/new.html.erb
<div class="text-center col-md-12 well">
  <div class="row"><h1>Novo Cargo</h1></div>
</div><br><br><br><br><br><br>

<%= render 'form' %>

app/views/jobs/show.html.erb
<div class="text-center col-md-12 well">
    <p>
      <strong>Cargo:</strong><br>
      <%= @job.job_name %>
    </p>
</div>

<div class="row text-center">
<% if logged_in? && current_user.admin?%>
    <%= link_to 'Editar', edit_job_path(@job), class:'btn btn-default' %>
<% end %>

<%= link_to 'Voltar', jobs_path, class:'btn btn-default' %>
</div>