config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :job_has_functions
  resources :meeting_has_members
  resources :members
  resources :jobs
  resources :meetings
  resources :functions
  resources :agendas
  resources :meetings

   root 'sessions#new'

  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

end

app/models/job_has_function.rb
class JobHasFunction < ActiveRecord::Base

	belongs_to :job
	belongs_to :function

end

app/controllers/job_has_functions_controller.rb
class JobHasFunctionsController < ApplicationController
  before_action :set_job_has_function, only: [:show, :edit, :update, :destroy]

  # GET /job_has_functions
  # GET /job_has_functions.json
  def index
    if logged_in?
      @job_has_functions = JobHasFunction.all
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /job_has_functions/1
  # GET /job_has_functions/1.json
  def show
    unless logged_in?
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /job_has_functions/new
  def new
    if logged_in? && current_user.admin?
      @job_has_function = JobHasFunction.new
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # GET /job_has_functions/1/edit
  def edit
    unless logged_in? && current_user.admin?
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # POST /job_has_functions
  # POST /job_has_functions.json
  def create
    if logged_in? && current_user.admin?
      @job_has_function = JobHasFunction.new(job_has_function_params)

      respond_to do |format|
        if @job_has_function.save
          format.html { redirect_to @job_has_function }
          format.json { render :show, status: :created, location: @job_has_function }
        else
          format.html { render :new }
          format.json { render json: @job_has_function.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # PATCH/PUT /job_has_functions/1
  # PATCH/PUT /job_has_functions/1.json
  def update
    if logged_in? && current_user.admin?
      respond_to do |format|
        if @job_has_function.update(job_has_function_params)
          format.html { redirect_to @job_has_function }
          format.json { render :show, status: :ok, location: @job_has_function }
        else
          format.html { render :edit }
          format.json { render json: @job_has_function.errors, status: :unprocessable_entity }
        end
      end
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  # DELETE /job_has_functions/1
  # DELETE /job_has_functions/1.json
  def destroy
    if logged_in? && current_user.admin?
      @job_has_function.destroy
      respond_to do |format|
        format.html { redirect_to job_has_functions_url }
        format.json { head :no_content }
      end
    else
      flash.now[:danger] = 'Você não possui autorização'
      render 'sessions/new'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_has_function
      @job_has_function = JobHasFunction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_has_function_params
      params.require(:job_has_function).permit(:job_id, :function_id)
    end
end

app/helpers/job_has_functions_helper.rb
module JobHasFunctionsHelper
end

app/views/job_has_functions/_form.html.erb
<div class="text-center well">
    <%= form_for(@job_has_function) do |f| %>

      <div class="field form-group">
        <%= f.label :job_id, "Cargo" %><br>
        <%= f.select :job_id, Job.all.collect { |m| [ m.job_name, m.id ] }, class:'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :function_id, "Função" %><br>
        <%= f.select :function_id, Function.all.collect { |m| [ m.function_name, m.id ] }, class:'form-control' %>
      </div>
      <div class="actions text-center">
        <%= f.submit "Criar Relação", class:'btn btn-success' %>
      </div><br>

      <div class="col-md-12 text-center">
        <%= link_to 'Voltar', job_has_functions_path, class: "btn btn-default" %>
      </div><br><br>

    <% end %>
</div>

app/views/job_has_functions/edit.html.erb
<div class="text-center col-md-12 well">
  <div class="row"><h1 class="enfeite-off"><%= link_to 'Editar Funcionalidade', member_path %></h1></div>
</div><br><br><br><br><br><br>

<%= render 'form' %>

app/views/job_has_functions/index.html.erb
<div class="container col-md-12 text-center well">
    <div class="row"><h1>Funcionalidades</h1></div>
</div>

<div class="row">
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="col-md-6">Cargo</th>
          <th class="col-md-6">Função</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @job_has_functions.each do |job_has_function| %>
          <tr>
            <td class="col-md-6"><%= job_has_function.job.job_name %></td>
            <td class="col-md-6"><%= job_has_function.function.function_name %></td>
            <td><%= link_to 'Show', job_has_function %></td>
            <td><%= link_to 'Edit', edit_job_has_function_path(job_has_function) %></td>
            <td><%= link_to 'Destroy', job_has_function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

<br>

<div class="container">
    <div class="row text-center col-md-12"><%= link_to 'Nova Funcionalidade', new_job_has_function_path, class: "btn btn-primary" %></div>
</div>

app/views/job_has_functions/new.html.erb
<div class="text-center col-md-12 well">
  <div class="row"><h1>Nova Funcionalidade</h1></div>
</div><br><br><br><br><br><br>

<%= render 'form' %>

app/views/job_has_functions/show.html.erb
<div class="text-center col-md-12 well">
    <p>
      <strong>Job:</strong><br>
      <%= @job_has_function.job.job_name %>
    </p>

    <p>
      <strong>Function:</strong><br>
      <%= @job_has_function.function.function_name %>
    </p>
</div>

<div class="row text-center ">
    <%= link_to 'Editar', edit_job_has_function_path(@job_has_function), class:'btn btn-default' %>
    <%= link_to 'Voltar', job_has_functions_path, class:'btn btn-default' %>
</div>