config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :job_has_functions
  resources :meeting_has_members
  resources :members
  resources :jobs
  resources :meetings
  resources :functions
  resources :agendas
  resources :meetings

   root 'sessions#new'

  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <%= link_to 'SCP', root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
                <li><%= link_to current_user.member_name, member_path(current_user.id) %></li>
                <li><%= link_to 'Pautas', agendas_path %></li>
                <li><%= link_to 'Reuniões', meetings_path %></li>
                <li><%= link_to 'Membros', members_path %></li>
                    <% if current_user.admin? %>
                        <li><%= link_to 'Cargos', jobs_path %></li>
                        <li><%= link_to 'Funções', functions_path %></li>
                        <li><%= link_to 'Funcionalidades', job_has_functions_path %></li>

                    <% end %>
                <li><%=link_to "Log out", logout_path, method: "delete" %></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SCP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
<%= yield %>
</div>
<%= debug(params) if Rails.env.development? %>

</body>
</html>